#! /bin/bash
DEST=/mnt/h/EDKTest/fd
TARGET=DEBUG
BOOT=/mnt/i
BOOTDEV='I:'

# cat YukiPkg/Application/HelloWorld/HelloWorld.inf.inc > YukiPkg/Application/HelloWorld/HelloWorld.inf
# cat YukiPkg/Include/lvgl.inf.inc >> YukiPkg/Application/HelloWorld/HelloWorld.inf
# cp -Rv YukiPkg/Application/HelloWorld/stdc/*.h YukiPkg/Application/HelloWorld


cat YukiPkg/Application/YukiLoader/YukiLoader.inf.inc > YukiPkg/Application/YukiLoader/YukiLoader.inf
cat YukiPkg/Include/lvgl.inf.inc >> YukiPkg/Application/YukiLoader/YukiLoader.inf
cat YukiPkg/Include/lv_sprintf.h > YukiPkg/Libs/lvgl/src/stdlib/lv_sprintf.h
cat YukiPkg/Include/jdmaster.c > YukiPkg/Libs/libjpeg-turbo/jdmaster.c
cat YukiPkg/Include/jmorecfg.h > YukiPkg/Libs/libjpeg-turbo/jmorecfg.h
cat YukiPkg/Include/pnglibconf.h > YukiPkg/Libs/libpng/pnglibconf.h

sudo mkdir -p $BOOT
sudo mount -t drvfs $BOOTDEV $BOOT

rm -rvf $BOOT/EFI
mkdir -p $BOOT/EFI/boot

build -p YukiPkg/YukiUEFI.dsc -b ${TARGET}
cp Build/YukiPkg/${TARGET}_GCC/X64/*.efi $DEST
cp Build/YukiPkg/${TARGET}_GCC/X64/*.efi $BOOT

# copy Shell to $BOOT
cp Build/Shell/DEBUG_GCC/X64/*.efi $BOOT
cp Build/Shell/DEBUG_GCC/X64/ShellPkg/Application/Shell/Shell/OUTPUT/Shell.efi $BOOT/EFI/boot/bootx64.efi

sudo umount $BOOT
sudo rm -rvf $BOOT
